"""DNS zone and record management service."""

import os
from datetime import datetime
from typing import List, Dict

from app.schemas.schemas import DNSRecordCreate, DNSZoneResponse

DNS_ZONES_DIR = os.getenv("DNS_ZONES_DIR", "/etc/bind/zones")


class DNSService:
    """Manages DNS zone files and records."""

    def _generate_zone_file(self, zone: str, records: List[Dict]) -> str:
        """Generate a BIND-format zone file."""
        serial = datetime.now().strftime("%Y%m%d%H")
        content = f"""; Zone file for {zone}
; Generated by NovaPanel
$TTL 3600
$ORIGIN {zone}.

@   IN  SOA ns1.{zone}. admin.{zone}. (
            {serial}   ; Serial
            3600       ; Refresh
            1800       ; Retry
            604800     ; Expire
            86400      ; Minimum TTL
)

; Nameservers
@       IN  NS  ns1.{zone}.
@       IN  NS  ns2.{zone}.

"""
        for record in records:
            priority_str = ""
            if record.get("priority") is not None:
                priority_str = f"{record['priority']} "

            content += f"{record['name']:<16} {record['ttl']:<8} IN  {record['type']:<8} {priority_str}{record['content']}\n"

        return content

    async def create_zone(self, zone_name: str) -> DNSZoneResponse:
        """Create a new DNS zone with default records."""
        os.makedirs(DNS_ZONES_DIR, exist_ok=True)

        default_records = [
            {"name": "@", "type": "A", "content": "0.0.0.0", "ttl": 3600, "priority": None},
            {"name": "www", "type": "CNAME", "content": f"{zone_name}.", "ttl": 3600, "priority": None},
            {"name": "@", "type": "MX", "content": f"mail.{zone_name}.", "ttl": 3600, "priority": 10},
        ]

        zone_content = self._generate_zone_file(zone_name, default_records)
        zone_path = os.path.join(DNS_ZONES_DIR, f"db.{zone_name}")

        with open(zone_path, "w") as f:
            f.write(zone_content)

        return DNSZoneResponse(
            zone=zone_name,
            records=default_records,
            status="created",
            message=f"DNS zone {zone_name} created with default records",
        )

    async def get_zone(self, zone_name: str) -> DNSZoneResponse:
        """Read and parse a DNS zone file."""
        zone_path = os.path.join(DNS_ZONES_DIR, f"db.{zone_name}")
        if not os.path.exists(zone_path):
            raise FileNotFoundError(f"Zone file not found: {zone_path}")

        records = []
        with open(zone_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith(";") or line.startswith("$"):
                    continue
                if "IN" in line and "SOA" not in line and "NS" not in line:
                    parts = line.split()
                    if len(parts) >= 5:
                        records.append({
                            "name": parts[0],
                            "ttl": int(parts[1]) if parts[1].isdigit() else 3600,
                            "type": parts[3],
                            "content": " ".join(parts[4:]),
                        })

        return DNSZoneResponse(
            zone=zone_name,
            records=records,
            status="active",
            message=f"Zone {zone_name} loaded with {len(records)} records",
        )

    async def add_record(self, req: DNSRecordCreate) -> DNSZoneResponse:
        """Add a DNS record to an existing zone."""
        zone_path = os.path.join(DNS_ZONES_DIR, f"db.{req.zone}")
        if not os.path.exists(zone_path):
            await self.create_zone(req.zone)

        priority_str = ""
        if req.priority is not None:
            priority_str = f"{req.priority} "

        record_line = f"{req.name:<16} {req.ttl:<8} IN  {req.record_type.value:<8} {priority_str}{req.content}\n"

        with open(zone_path, "a") as f:
            f.write(record_line)

        result = await self.get_zone(req.zone)
        result.message = f"Record {req.name} ({req.record_type.value}) added to {req.zone}"
        return result

    async def delete_record(self, zone_name: str, record_name: str, record_type: str) -> str:
        """Delete a DNS record from a zone file."""
        zone_path = os.path.join(DNS_ZONES_DIR, f"db.{zone_name}")
        if not os.path.exists(zone_path):
            raise FileNotFoundError(f"Zone file not found: {zone_path}")

        with open(zone_path, "r") as f:
            lines = f.readlines()

        new_lines = []
        removed = False
        for line in lines:
            stripped = line.strip()
            if record_name in stripped and record_type in stripped and "IN" in stripped:
                removed = True
                continue
            new_lines.append(line)

        if not removed:
            raise Exception(f"Record {record_name} ({record_type}) not found in zone {zone_name}")

        with open(zone_path, "w") as f:
            f.writelines(new_lines)

        return f"Record {record_name} ({record_type}) deleted from {zone_name}"
